services:
  app:
    image: ghcr.io/slfhstd/deletedposts:latest
    container_name: mch-deletedposts
    restart: unless-stopped
    volumes:
      - /docker/data/deletedposts:/app/config
    environment:
      CLIENT_ID: "${CLIENT_ID}"
      CLIENT_SECRET: "${CLIENT_SECRET}"
      USER_AGENT: "${USER_AGENT}"
      USERNAME: "${USERNAME}"
      PASSWORD: "${PASSWORD}"
      SUB_NAME: "${SUB_NAME}"
      MAX_DAYS: "${MAX_DAYS}"            # strings are converted to ints when the
      MAX_POSTS: "${MAX_POSTS}"          # corresponding config value is an int
      SLEEP_MINUTES: "${SLEEP_MINUTES}"  
